# Generated by Django 4.0.2 on 2022-02-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, null=True, verbose_name='نام و نام خانوادگی')),
                ('vekalat_id', models.CharField(max_length=120, null=True, verbose_name='شماره پروانه وکالت')),
                ('vaxiat_isargari', models.CharField(choices=[('25', '25%'), ('50', '50%'), ('75', '75%'), ('90', '90%')], max_length=2, null=True, verbose_name='وضعیت ایثارگری')),
                ('national_id', models.CharField(max_length=30, null=True, verbose_name='کد ملی')),
                ('osviat_kanoon_vokala', models.CharField(max_length=70, null=True, verbose_name='عضویت کانون وکلا')),
            ],
        ),
    ]
